### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by hrueger** [hrueger/AGLight#143]
- [ ] Fixtures padding between
- [ ] ButtonGrid
- [ ] More Effects
- [ ] FPS Display
- [ ] autoremove widgets when removing fixture
- [ ] transition time in seconds
- [ ] fixed channel value dialog live preview
- [ ] second click on color field should make color black
- [ ] blackout only for some fixtures
- [ ] switch on off buttons
- [x] move to JSON file format

**Comment by hrueger** [comment]
All moved to specific issues, see #151, #152, #153, #154, #155, #156, #157, #158 and #159
